import { Montserrat } from 'next/font/google'
import localFont from 'next/font/local'

import type { Metadata } from 'next'
import './globals.css'

const montserrat = Montserrat({
  variable: '--font-montserrat',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
})

const tradeGothic = localFont({
  src: [
    {
      path: '../../public/fonts/TradeGothicLTExtended-Bold.otf',
      weight: '700',
    },
    {
      path: '../../public/fonts/TradeGothicLTExtended-Regular.otf',
      weight: '400',
    },
  ],
  variable: '--font-trade-gothic',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`$${tradeGothic.variable} ${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
